data_root: data

data_ingestion:
  root_dir: data/raw
  source_url: https://raw.githubusercontent.com/MusaddiqueHussainLabs/datasets/main/github_issues_full.tsv
  local_data_file: data/raw/github_issues_full.tsv